### PR TITLE
fix get mac by iface

### PR DESCRIPTION
**Pull request by linevers1926**
solve in windows can't get mac by iface.

https://github.com/bevry/getmac/issues/32

### CODE REVIEW

**Comment by balupton** [comment]
I've resolved the merge conflict, but can anyone explain to me what this actually means, and what it does

once I know what this is doing and changing, then happy to merge - I need more details, as we have no test environment against windows

**Comment by linevers1926** [comment]
fix get mac by iface

**Comment by linevers1926** [comment]
solve in windows can't get mac by iface

**Comment by balupton** [comment]
Please rebase with master, and add some tests for the differences that this method exposes, such as a fixture of the different input to justify the code changes, as currently there is no fixture provided to justify the changes to the regex and the command.

**Comment by balupton** [comment]
v4 does away with the need for this

**Pull request closed without merging**
